# Generated by Django 4.1.7 on 2023-03-07 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users_following",
            field=models.ManyToManyField(
                related_name="books_followed", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
