# Generated by Django 4.1.7 on 2023-03-06 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Copy",
        ),
    ]
