# Generated by Django 4.1.7 on 2023-03-10 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="date_expected_devolution",
            field=models.DateField(default=datetime.date(2023, 3, 27)),
        ),
    ]
