# Generated by Django 4.1.7 on 2023-03-13 13:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0003_alter_loans_date_expected_devolution"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_loan", models.DateField(auto_now_add=True)),
                (
                    "date_expected_devolution",
                    models.DateField(default=datetime.date(2023, 3, 28)),
                ),
                ("date_devolution", models.DateField(null=True)),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_copy",
                        to="copies.copy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Loans",
        ),
        migrations.AlterField(
            model_name="copy",
            name="user",
            field=models.ManyToManyField(
                related_name="copies",
                through="copies.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
