# Generated by Django 4.1.7 on 2023-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="date_expected_devolution",
            field=models.DateField(null=True),
        ),
    ]
